name: collegiateleader.org
favicon: null
layout_spectrum: 0.50813
typography_spectrum: 0.62431
title: 'The purpose of the Collegiate Leadership Competition (CLC) is to create a leadership "practice field".'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7a0000'
    - '#bcc500'
    - '#a95757'
    - '#333333'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
